import type { AsanaDefinition } from "../../../types/asana-definition";

export const balasanaPose: AsanaDefinition = {
  id: "balasana",
  name: "Child's Pose",
  displayName: "Child's Pose",
  sanskritName: "Bālāsana",
  category: "restorative",
  difficulty: "beginner",
  requiredLandmarks: [11, 12, 13, 14, 23, 24, 25, 26, 27, 28],
  description: "A restorative resting pose with hips resting on heels and torso folded forward over thighs.",
  aliases: ["childs-pose", "child-pose"],
  rules: [
    {
      id: "balasana.hip.flexion",
      name: "Hip Fold to Heels",
      metric: "angle",
      points: [11, 23, 25],
      comparison: "between",
      min: 20,
      max: 80,
      tolerance: 15,
      warningTolerance: 25,
      weight: 3,
      severity: "high",
      feedback: "Send your hips back toward your heels and soften your torso down.",
    },
    {
      id: "balasana.knee.flexion",
      name: "Deep Knee Bend",
      metric: "angle",
      points: [23, 25, 27],
      comparison: "between",
      min: 20,
      max: 80,
      tolerance: 15,
      warningTolerance: 25,
      weight: 2,
      severity: "high",
      feedback: "Keep your knees folded comfortably under your torso or wide to the mat edges.",
    },
    {
      id: "balasana.arms.extension",
      name: "Arms Forward Extension",
      metric: "angle",
      points: [11, 13, 15],
      comparison: "between",
      min: 140,
      max: 180,
      tolerance: 15,
      warningTolerance: 20,
      weight: 1,
      severity: "low",
      feedback: "Extend your arms forward with palms resting softly on the mat.",
    },
  ],
};
