import type { AsanaDefinition } from "../../../types/asana-definition";

export const bhujangasanaPose: AsanaDefinition = {
  id: "bhujangasana",
  name: "Cobra Pose",
  displayName: "Cobra Pose",
  sanskritName: "Bhujaṅgāsana",
  category: "backbend",
  difficulty: "beginner",
  requiredLandmarks: [11, 12, 13, 14, 23, 24, 25],
  description: "A prone backbend opening the chest and strengthening the spine.",
  aliases: ["cobra-pose", "cobra"],
  rules: [
    {
      id: "bhujangasana.chest.lift",
      name: "Chest Lift Extension",
      metric: "angle",
      points: [11, 23, 25],
      comparison: "between",
      min: 125,
      max: 175,
      tolerance: 15,
      warningTolerance: 20,
      weight: 3,
      severity: "high",
      feedback: "Lift your chest off the mat using your back muscles while keeping your hips grounded.",
    },
    {
      id: "bhujangasana.elbows.tuck",
      name: "Elbow Bend & Tuck",
      metric: "angle",
      points: [11, 13, 15],
      comparison: "between",
      min: 80,
      max: 145,
      tolerance: 15,
      warningTolerance: 20,
      weight: 2,
      severity: "high",
      feedback: "Keep a soft bend in your elbows and hug them close to your ribcage.",
    },
    {
      id: "bhujangasana.shoulders.level",
      name: "Shoulder Level",
      metric: "horizontal_alignment",
      points: [11, 12],
      comparison: "less_than",
      target: 0.08,
      tolerance: 0.04,
      warningTolerance: 0.08,
      weight: 2,
      severity: "medium",
      feedback: "Roll your shoulders back and down away from your ears.",
    },
    {
      id: "bhujangasana.hips.grounded",
      name: "Pelvis Grounding",
      metric: "horizontal_alignment",
      points: [23, 24],
      comparison: "less_than",
      target: 0.08,
      tolerance: 0.04,
      warningTolerance: 0.08,
      weight: 1,
      severity: "medium",
      feedback: "Keep your pelvis and thighs grounded into the floor.",
    },
  ],
};
