import type { AsanaDefinition } from "../../../types/asana-definition";

export const chaturangaPose: AsanaDefinition = {
  id: "chaturanga-dandasana",
  name: "Four-Limbed Staff Pose",
  displayName: "Four-Limbed Staff Pose",
  sanskritName: "Caturaṅga Daṇḍāsana",
  category: "core",
  difficulty: "intermediate",
  requiredLandmarks: [11, 12, 13, 14, 15, 16, 23, 24, 27, 28],
  description: "A low plank posture requiring core engagement, shoulder stability, and 90-degree elbow flexion.",
  aliases: ["chaturanga", "four-limbed-staff-pose", "low-plank"],
  rules: [
    {
      id: "chaturanga.left_elbow.angle",
      name: "Left Elbow 90-Degree Bend",
      metric: "angle",
      points: [11, 13, 15],
      comparison: "between",
      min: 75,
      max: 110,
      tolerance: 15,
      warningTolerance: 20,
      weight: 3,
      severity: "high",
      feedback: "Keep your elbows bent at 90 degrees and hugged tight against your ribs.",
    },
    {
      id: "chaturanga.right_elbow.angle",
      name: "Right Elbow 90-Degree Bend",
      metric: "angle",
      points: [12, 14, 16],
      comparison: "between",
      min: 75,
      max: 110,
      tolerance: 15,
      warningTolerance: 20,
      weight: 3,
      severity: "high",
      feedback: "Keep your elbows bent at 90 degrees and hugged tight against your ribs.",
    },
    {
      id: "chaturanga.body.line",
      name: "Straight Body Plank Line",
      metric: "angle",
      points: [11, 23, 27],
      comparison: "between",
      min: 155,
      max: 185,
      tolerance: 15,
      warningTolerance: 20,
      weight: 3,
      severity: "high",
      feedback: "Engage your core firmly to prevent your hips from sagging toward the mat.",
    },
    {
      id: "chaturanga.shoulders.level",
      name: "Shoulder Level",
      metric: "horizontal_alignment",
      points: [11, 12],
      comparison: "less_than",
      target: 0.06,
      tolerance: 0.03,
      warningTolerance: 0.06,
      weight: 1,
      severity: "medium",
      feedback: "Keep your shoulders level and avoid collapsing through your chest.",
    },
  ],
};
