import type { AsanaDefinition } from "../../../types/asana-definition";

export const downwardDogPose: AsanaDefinition = {
  id: "adho-mukha-svanasana",
  name: "Downward-Facing Dog",
  displayName: "Downward-Facing Dog",
  sanskritName: "Adho Mukha Śvānāsana",
  category: "inversion",
  difficulty: "beginner",
  requiredLandmarks: [11, 12, 13, 14, 23, 24, 25, 26, 27, 28],
  description: "An inverted V-shape posture decompressing the spine and stretching the hamstrings and calves.",
  aliases: ["downward-facing-dog", "downward-dog", "down-dog"],
  rules: [
    {
      id: "downward-dog.hips.inverted_v",
      name: "Inverted V Hip Peak",
      metric: "angle",
      points: [11, 23, 27],
      comparison: "between",
      min: 65,
      max: 115,
      tolerance: 15,
      warningTolerance: 20,
      weight: 3,
      severity: "high",
      feedback: "Lift your hips high and back to form a steady inverted V-shape.",
    },
    {
      id: "downward-dog.arms.extension",
      name: "Arm & Shoulder Push",
      metric: "angle",
      points: [11, 13, 15],
      comparison: "between",
      min: 150,
      max: 180,
      tolerance: 15,
      warningTolerance: 20,
      weight: 2,
      severity: "high",
      feedback: "Press firmly through your palms and straighten your arms.",
    },
    {
      id: "downward-dog.legs.extension",
      name: "Leg Extension",
      metric: "angle",
      points: [23, 25, 27],
      comparison: "between",
      min: 145,
      max: 180,
      tolerance: 15,
      warningTolerance: 20,
      weight: 2,
      severity: "medium",
      feedback: "Lengthen the backs of your legs without locking your knees.",
    },
    {
      id: "downward-dog.shoulders.level",
      name: "Shoulder Level",
      metric: "horizontal_alignment",
      points: [11, 12],
      comparison: "less_than",
      target: 0.06,
      tolerance: 0.03,
      warningTolerance: 0.06,
      weight: 1,
      severity: "medium",
      feedback: "Keep your upper back broad and shoulders level.",
    },
  ],
};
