import type { AsanaDefinition } from "../../../types/asana-definition";

export const mountainPose: AsanaDefinition = {
  id: "mountain-pose",
  name: "Mountain Pose",
  displayName: "Mountain Pose",
  sanskritName: "Tadasana",
  category: "standing",
  difficulty: "beginner",
  requiredLandmarks: [11, 12, 23, 24, 25, 27],
  description: "The foundational standing posture establishing alignment, balance, and centered awareness.",
  aliases: ["tadasana", "step-12-mountain-tadasana"],
  rules: [
    {
      id: "mountain.shoulders.level",
      name: "Shoulder Level",
      metric: "horizontal_alignment",
      points: [11, 12],
      comparison: "less_than",
      target: 0.05,
      tolerance: 0.03,
      warningTolerance: 0.06,
      weight: 1,
      severity: "medium",
      feedback: "Keep shoulders level and relaxed away from your ears.",
    },
    {
      id: "mountain.hips.level",
      name: "Hip Alignment",
      metric: "horizontal_alignment",
      points: [23, 24],
      comparison: "less_than",
      target: 0.06,
      tolerance: 0.03,
      warningTolerance: 0.07,
      weight: 1,
      severity: "medium",
      feedback: "Distribute your weight evenly and keep your hips level.",
    },
    {
      id: "mountain.spine.vertical",
      name: "Spine Alignment",
      metric: "vertical_alignment",
      points: [11, 23],
      comparison: "less_than",
      target: 0.07,
      tolerance: 0.04,
      warningTolerance: 0.09,
      weight: 2,
      severity: "high",
      feedback: "Lengthen your spine vertically without leaning forward or to the side.",
    },
    {
      id: "mountain.left_leg.straight",
      name: "Left Leg Straight",
      metric: "angle",
      points: [23, 25, 27],
      comparison: "between",
      min: 160,
      max: 180,
      tolerance: 15,
      warningTolerance: 20,
      weight: 2,
      severity: "high",
      feedback: "Keep your left leg straight and active.",
    },
    {
      id: "mountain.right_leg.straight",
      name: "Right Leg Straight",
      metric: "angle",
      points: [24, 26, 28],
      comparison: "between",
      min: 160,
      max: 180,
      tolerance: 15,
      warningTolerance: 20,
      weight: 2,
      severity: "high",
      feedback: "Keep your right leg straight and active.",
    },
  ],
};
