import type { AsanaDefinition } from "../../../types/asana-definition";

export const padmasanaPose: AsanaDefinition = {
  id: "padmasana",
  name: "Lotus Pose",
  displayName: "Lotus Pose",
  sanskritName: "Padmāsana",
  category: "seated",
  difficulty: "advanced",
  requiredLandmarks: [11, 12, 13, 14, 23, 24],
  description: "A cross-legged seated posture that encourages stillness, spinal alignment, and steady breathing.",
  aliases: ["lotus-pose", "lotus"],
  rules: [
    {
      id: "padmasana.spine.vertical",
      name: "Upright Spine",
      metric: "vertical_alignment",
      points: [11, 23],
      comparison: "less_than",
      target: 0.08,
      tolerance: 0.04,
      warningTolerance: 0.08,
      weight: 3,
      severity: "high",
      feedback: "Sit tall on your sitting bones and lengthen your spine toward the ceiling.",
    },
    {
      id: "padmasana.shoulders.level",
      name: "Shoulder Balance",
      metric: "horizontal_alignment",
      points: [11, 12],
      comparison: "less_than",
      target: 0.06,
      tolerance: 0.03,
      warningTolerance: 0.06,
      weight: 2,
      severity: "medium",
      feedback: "Relax your shoulders evenly away from your ears.",
    },
    {
      id: "padmasana.hips.level",
      name: "Grounded Hips",
      metric: "horizontal_alignment",
      points: [23, 24],
      comparison: "less_than",
      target: 0.07,
      tolerance: 0.03,
      warningTolerance: 0.07,
      weight: 2,
      severity: "medium",
      feedback: "Distribute your weight equally across both sitting bones.",
    },
    {
      id: "padmasana.arms.relaxed",
      name: "Relaxed Arms",
      metric: "angle",
      points: [11, 13, 15],
      comparison: "between",
      min: 80,
      max: 175,
      tolerance: 15,
      warningTolerance: 20,
      weight: 1,
      severity: "low",
      feedback: "Rest your hands gently on your knees with arms relaxed.",
    },
  ],
};
