import type { AsanaDefinition } from "../../../types/asana-definition";

export const setuBandhasanaPose: AsanaDefinition = {
  id: "setu-bandhasana",
  name: "Bridge Pose",
  displayName: "Bridge Pose",
  sanskritName: "Setu Bandhāsana",
  category: "backbend",
  difficulty: "beginner",
  requiredLandmarks: [11, 12, 23, 24, 25, 26, 27, 28],
  description: "A supine backbend lifting the pelvis and opening the chest and hip flexors.",
  aliases: ["bridge-pose", "bridge"],
  rules: [
    {
      id: "bridge.hips.lift",
      name: "Pelvic Bridge Lift",
      metric: "angle",
      points: [11, 23, 25],
      comparison: "between",
      min: 140,
      max: 185,
      tolerance: 15,
      warningTolerance: 20,
      weight: 3,
      severity: "high",
      feedback: "Press through your heels and lift your hips high toward the ceiling.",
    },
    {
      id: "bridge.left_knee.angle",
      name: "Left Knee Stacking",
      metric: "angle",
      points: [23, 25, 27],
      comparison: "between",
      min: 70,
      max: 115,
      tolerance: 15,
      warningTolerance: 20,
      weight: 2,
      severity: "high",
      feedback: "Stack your knees directly over your ankles with thighs parallel.",
    },
    {
      id: "bridge.right_knee.angle",
      name: "Right Knee Stacking",
      metric: "angle",
      points: [24, 26, 28],
      comparison: "between",
      min: 70,
      max: 115,
      tolerance: 15,
      warningTolerance: 20,
      weight: 2,
      severity: "high",
      feedback: "Stack your knees directly over your ankles with thighs parallel.",
    },
    {
      id: "bridge.shoulders.grounded",
      name: "Shoulder Grounding",
      metric: "horizontal_alignment",
      points: [11, 12],
      comparison: "less_than",
      target: 0.06,
      tolerance: 0.03,
      warningTolerance: 0.06,
      weight: 1,
      severity: "medium",
      feedback: "Keep your shoulders grounded and broad across the upper back.",
    },
  ],
};
