import type { AsanaDefinition } from "../../../types/asana-definition";

export const treePose: AsanaDefinition = {
  id: "tree-pose",
  name: "Tree Pose",
  sanskritName: "Vrksasana",
  category: "Balance",
  difficulty: "beginner",
  description: "A single-leg standing balance cultivating poise, focus, and core stability.",
  aliases: ["vrksasana"],
  rules: [
    {
      id: "tree.standing_leg.straight",
      name: "Standing Leg Straight",
      metric: "angle",
      points: [23, 25, 27],
      comparison: "between",
      min: 155,
      max: 180,
      tolerance: 15,
      warningTolerance: 20,
      weight: 3,
      severity: "high",
      feedback: "Keep your standing leg fully straight and grounded.",
    },
    {
      id: "tree.raised_knee.bent",
      name: "Raised Knee Position",
      metric: "angle",
      points: [24, 26, 28],
      comparison: "between",
      min: 25,
      max: 95,
      tolerance: 15,
      warningTolerance: 25,
      weight: 3,
      severity: "high",
      feedback: "Bend your raised leg and press your foot against the inner thigh or calf.",
    },
    {
      id: "tree.hips.level",
      name: "Hip Alignment",
      metric: "horizontal_alignment",
      points: [23, 24],
      comparison: "less_than",
      target: 0.08,
      tolerance: 0.04,
      warningTolerance: 0.08,
      weight: 2,
      severity: "high",
      feedback: "Square and level your hips forward.",
    },
    {
      id: "tree.shoulders.level",
      name: "Shoulder Alignment",
      metric: "horizontal_alignment",
      points: [11, 12],
      comparison: "less_than",
      target: 0.07,
      tolerance: 0.04,
      warningTolerance: 0.07,
      weight: 1,
      severity: "medium",
      feedback: "Keep shoulders relaxed and level with hands in prayer.",
    },
    {
      id: "tree.spine.vertical",
      name: "Torso Upright",
      metric: "vertical_alignment",
      points: [11, 23],
      comparison: "less_than",
      target: 0.08,
      tolerance: 0.04,
      warningTolerance: 0.08,
      weight: 2,
      severity: "high",
      feedback: "Lengthen your spine upward without leaning sideways.",
    },
  ],
};
