import type { AsanaDefinition } from "../../../types/asana-definition";

export const warriorIIPose: AsanaDefinition = {
  id: "warrior-ii",
  name: "Warrior II",
  sanskritName: "Virabhadrasana II",
  category: "Standing",
  difficulty: "intermediate",
  description: "A powerful standing posture opening hips and chest while developing focus and stamina.",
  aliases: ["virabhadrasana-ii", "warrior-2"],
  rules: [
    {
      id: "warrior2.front_knee.angle",
      name: "Front Knee Bend",
      metric: "angle",
      points: [23, 25, 27],
      comparison: "between",
      min: 75,
      max: 125,
      tolerance: 15,
      warningTolerance: 25,
      weight: 3,
      severity: "high",
      feedback: "Bend your front knee toward 90 degrees — stack it directly over your ankle.",
    },
    {
      id: "warrior2.back_leg.straight",
      name: "Back Leg Straight",
      metric: "angle",
      points: [24, 26, 28],
      comparison: "between",
      min: 155,
      max: 180,
      tolerance: 15,
      warningTolerance: 20,
      weight: 2,
      severity: "high",
      feedback: "Keep your back leg straight and strong.",
    },
    {
      id: "warrior2.left_arm.extension",
      name: "Left Arm Extension",
      metric: "angle",
      points: [11, 13, 15],
      comparison: "between",
      min: 155,
      max: 180,
      tolerance: 15,
      warningTolerance: 20,
      weight: 2,
      severity: "high",
      feedback: "Extend your left arm straight out to the side.",
    },
    {
      id: "warrior2.right_arm.extension",
      name: "Right Arm Extension",
      metric: "angle",
      points: [12, 14, 16],
      comparison: "between",
      min: 155,
      max: 180,
      tolerance: 15,
      warningTolerance: 20,
      weight: 2,
      severity: "high",
      feedback: "Extend your right arm straight out to the side.",
    },
    {
      id: "warrior2.left_arm.shoulder_height",
      name: "Left Arm Height",
      metric: "angle",
      points: [13, 11, 23],
      comparison: "between",
      min: 75,
      max: 115,
      tolerance: 15,
      warningTolerance: 25,
      weight: 2,
      severity: "high",
      feedback: "Lift your left arm to shoulder height parallel to the floor.",
    },
    {
      id: "warrior2.right_arm.shoulder_height",
      name: "Right Arm Height",
      metric: "angle",
      points: [14, 12, 24],
      comparison: "between",
      min: 75,
      max: 115,
      tolerance: 15,
      warningTolerance: 25,
      weight: 2,
      severity: "high",
      feedback: "Lift your right arm to shoulder height parallel to the floor.",
    },
    {
      id: "warrior2.shoulders.level",
      name: "Shoulder Level",
      metric: "horizontal_alignment",
      points: [11, 12],
      comparison: "less_than",
      target: 0.06,
      tolerance: 0.03,
      warningTolerance: 0.06,
      weight: 1,
      severity: "medium",
      feedback: "Keep shoulders level and relaxed down away from your ears.",
    },
    {
      id: "warrior2.hips.level",
      name: "Hip Alignment",
      metric: "horizontal_alignment",
      points: [23, 24],
      comparison: "less_than",
      target: 0.08,
      tolerance: 0.04,
      warningTolerance: 0.08,
      weight: 1,
      severity: "medium",
      feedback: "Keep hips open and level toward the side.",
    },
    {
      id: "warrior2.torso.vertical",
      name: "Torso Upright",
      metric: "vertical_alignment",
      points: [11, 23],
      comparison: "less_than",
      target: 0.08,
      tolerance: 0.04,
      warningTolerance: 0.08,
      weight: 1,
      severity: "medium",
      feedback: "Keep your torso tall and upright without leaning forward.",
    },
  ],
};
