export type CoachingIntent =
  | "GUIDE_ENTRY"
  | "CORRECT"
  | "ACKNOWLEDGE_IMPROVEMENT"
  | "CONFIRM_RESOLUTION"
  | "CONFIRM_GOOD_FORM"
  | "ENCOURAGE_HOLD"
  | "CELEBRATE_COMPLETION"
  | "SAFETY_WARNING";
